[package]
name = "shellcode_loader"
version = "0.1.0"
authors = ["Pegleg <pegleg@linux.com>"]
edition = "2018"

[dependencies]
libc = { version = "0.2.71", features=[] }


[profile.release]
opt-level = 'z'
codegen-units = 1
panic = 'abort'


