[package]
name = "shellcoder"
version = "0.1.0"
authors = ["Pegleg <pegleg@linux.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = { version = "*", features=[] }

[profile.release]
panic = "abort"


